

services:
  db:
    image: postgres:16
    env_file: .env
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=C --lc-ctype=C
    ports:
      - "5432:5432"              # чтобы ты мог подключаться с хоста (manage.py)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
