# Generated by Django 5.2.7 on 2025-10-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_landing', '0002_alter_homepagecontent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
