# Generated by Django 5.2.7 on 2025-10-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_landing', '0003_alter_homepagecontent_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
