# Generated by Django 5.2.7 on 2025-10-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_landing', '0004_homepagetexts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagecontent',
            options={'verbose_name': '"About us" page content', 'verbose_name_plural': '"About us" page content'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Courses', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='homepagecontent',
            options={'verbose_name': 'Home page content', 'verbose_name_plural': 'Home page content'},
        ),
        migrations.AlterModelOptions(
            name='homepagetexts',
            options={'verbose_name': 'Home page texts', 'verbose_name_plural': 'Home page texts'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='content',
            field=models.TextField(verbose_name='"About us" text'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_description',
            field=models.TextField(verbose_name='Full description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Course image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(max_length=300, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Course name'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='main_title',
            field=models.CharField(max_length=200, verbose_name='Main header'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(max_length=100, verbose_name='Name of the site'),
        ),
    ]
