# Generated by Django 5.2.7 on 2025-10-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_landing', '0005_alter_aboutpagecontent_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
    ]
