# Generated by Django 5.2.7 on 2025-10-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_landing', '0006_homepagecontent_subtitle_homepagecontent_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
