# Generated by Django 5.2.7 on 2025-10-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_landing', '0007_course_goal_course_language_course_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='text',
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Subtitle'),
        ),
    ]
