# Generated by Django 5.2.7 on 2025-10-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_landing', '0008_remove_homepagecontent_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='subtitle',
            field=models.CharField(max_length=300, verbose_name='Subtitle'),
        ),
    ]
